accordion:
  controls: arrow # arrow | plus-minus
  copyButton:
    ariaLabel: Copy page section link to clipboard
    successText: Copied page section link to clipboard
    symbol: §
  globalControls:
    collapseText: Collapse All
    expandText: Expand All

analytics:
  googleId: 'GTM-NRDC63K'

bylineFormat: string # name | name-title | false

bibliography:
  displayOnPage: true
  displayShort: true
  heading: Bibliography

citations:
  divider: ', '
  popupStyle: text # text | icon

entryPage:
  sideBySide: false
  objectLinkText: View in Collection

epub:
  defaultCoverImage: 'cover-full.jpg'
  outputDir: '_epub'

footnotes:
  backlinkSymbol: '↩'

figures:
  assetDir: '/_assets/'
  enableModal: true
  imageDir: '/_assets/images'

licenseIcons: true

localization:
  defaultLocale: en-us

menuType: full # full | brief

navigation:
  nextButtonText: Next
  prevButtonText: Back

pageTitle:
  labelDivider: '. '

pdf:
  filename: getty-research-journal-19

ref:
  sequenceTransition: 30

searchEnabled: true

tableOfContents:
  contributorDivider: ' — '
